---
name: "Smart Stream"
description: "Advanced IP camera streaming to multiple platforms (YouTube, Twitch, Custom RTMP) with ONVIF support"
version: 1.0.8
slug: smart_stream
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386

# Home Assistant specific configuration
ingress: true
ingress_port: 3303
panel_icon: mdi:camera-wireless
panel_title: Smart Stream
homeassistant_api: true

# Ports configuration
ports:
  "3303/tcp": 3303

ports_description:
  "3303/tcp": "Web UI and API Port"

# Options schema
options:
  port: 3303
  log_level: "info"
  discovery_interface: ""
  
schema:
  port: "port"
  log_level: "list(debug|info|warn|error)"
  discovery_interface: "str"

# Startup configuration
startup: application

# Map configuration for persistent storage
map:
  - "share:rw"
  - "media:rw"

# Web UI configuration
webui: "http://[HOST]:[PORT:3303]"

# Watchdog configuration for health monitoring
watchdog: "http://[HOST]:[PORT:3303]/health"

# Documentation
url: "https://github.com/your-repo/smart-stream"

# Services
services:
  - "mqtt:want"

# Security
hassio_api: true
hassio_role: "default"
host_network: true
privileged:
  - "SYS_ADMIN"
full_access: false
apparmor: false
